### ISSUE TITLE
PMKID support?

### ISSUE THREAD

**Issue by dec0dOS** [dizcza/hashcat-wpa-server#1]
Hello! Thanks for awesome project!

What about pmkid attack support?

**Comment by dizcza** [comment]
Thanks, I was not aware that somebody uses my project. It started as a toy project, I don't play with it often currently, but I have spare time to improve things and consider your feature requests.

PMKID support is a good one to start one. Although, 22000 is superior to 16800 now (I recommend you to take a look at 22000). Here is a full list of hashcat modes that should be supported: 2500, 2501, 16800, 16801, 22000, 22001. I need to change the logic in order to support these and future capture file formats. I'll start doing this shortly, but it'll take time because it's not my current priority.

**Comment by dizcza** [comment]
I'll try to incorporate the workflow suggested in https://github.com/ZerBea/hcxtools/issues/150.

**Comment by ZerBea** [comment]
2200x is the successor of 250x and 1680x. Running the new hash mode we will get full benefit of reuse of PBKDF2 over PMKID and EAPOL.  
https://github.com/hashcat/hashcat/issues/1816
https://github.com/magnumripper/JohnTheRipper/issues/4183

**Comment by dizcza** [comment]
Yeap. That's why I've moved the logic to 22000 eventually. Since the commit on Jun 12, I convert each input file to 22000. Don't know when hashcat v6.0.0 is released, but the current master branch works seamlessly.

@dec0dOS give it a try

**Comment by dec0dOS** [comment]
Having several problems running hashcat-wpa-server on Windows. 

GPU passthrough in WSL2 and new docker release would help a lot.

**Comment by dizcza** [comment]
@dec0dOS please try again

**Comment by dec0dOS** [comment]
PMKID attack works fine! Great job, again, thank you for awesome project!
