### ISSUE TITLE
UI/UX improvements

### ISSUE THREAD

**Issue by dec0dOS** [dizcza/hashcat-wpa-server#2]
I think that UI/UX part is not very important for such a project. Anyway adding something simple like bootstrap css could greatly improve the user experience at almost no cost.

**Comment by dizcza** [comment]
Well well, UI was indeed beyond the scope. But I find bootstrap quite neat. Let's see what I can do with the design.

Meanwhile, I'm still adding features. For example, I'm planning to include a choice over countries to target first names as password candidates. Currently, only Ukrainian and Russian names are included.

**Comment by dizcza** [comment]
I've added bootstrap. Feel free to change the UI to how you prefer and come up with a PR.

**Comment by dec0dOS** [comment]
I don't think there is anything that needs to be changed.
The only thing is the homepage. How about adding some compact description about the project via jumbotron component?

**Comment by dizcza** [comment]
All right, I added a jumbotron component.

**Comment by dizcza** [comment]
I just found a regression bug, introduced on Jun 21. The attack result status was always shown as Completed since then. But it didn't run the attack.
So if you started any tasks since Jun 21, you need to restart them again followed by removing `essid_tried` in the directory where the database is stored on your host machine - run `docker volume inspect hashcat-database` to find the folder location (it's not `~/hashcat_database` anymore).

Having tests running on deploy would prevent it, of course. It's a lot of effort though, especially since I've never written tests for a flask app. I'll set the tests up, but don't expect it to happen soon.
